# Website details
name: The Sound Of Crickets
description: Gaming, Anime, Politics.
email: thesoundofcrickets@protonmail.com
author: Chirp!
lang: en
locale: en_US

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/Denver
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://thesoundofcrickets.com

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
